services:
  # Backend API Service
  - type: web
    name: reslink-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: reslink-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    
  # Frontend Static Site  
  - type: web
    name: reslink-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npx vite build --mode production
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://reslink-backend.onrender.com/api

databases:
  - name: reslink-db
    databaseName: reslink
    user: reslink_user
    plan: free